import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Sidebar from "@/app/components/sidebar/sidebar";
import style from "./page.module.scss"

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
									   children,
								   }: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<div className="app">
			<Sidebar/>
			<main className={style.content}>{children}</main>
		</div>
		</body>
		</html>
	)
}
