import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Link from "next/link";
import Sidebar from "@/app/components/sidebar/sidebar";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
									   children,
								   }: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
		<body className={inter.className}>
		<div className="app">
			<Sidebar/>
			<div>{children}</div>
		</div>
		</body>
		</html>
	)
}
